version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db: 
    image: postgres
    env_file:
      - .env
    volumes:
      - db-data:/db-
      
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:5050
    depends_on:
      - db
    env_file:
      - .env
  
  redis: 
    image: redis
    env_file:
      - .env
    volumes: 
      - cache-data:/cache-data

volumes:
  db-data:
  cache-data:
