version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    depends_on:
      - db
      - redis

  db: 
    image: postgres
    environment: 
      POSTGRES_USER: supremeleader
      POSTGRES_PASSWORD: chetfunches
      POSTGRES_DB: postgres
    volumes:
     - db-data:/db-data
  
  redis: 
    image: redis
    volumes: 
      - cache-data:/cache-data

volumes:
  db-data:
  cache-data:
